BIN         =./bin
DEPLOY_DIR	=../Libraries/libDatabaseAPI.so
SRC			=./src
INCLUDE		=-I./include \
			-I../VideoModule/include \
		  
CXX=g++

CXXFLAGS=-c

CXXFLAGS+=g

LIBOBJS = $(BIN)/DatabaseVideoData.o