INCLUDE_PATH=include/
SRC_PATH=src/
BIN_PATH=bin/

libraries:
	cd $(SRC_PATH)	
	g++ -c $(INCLUDE_PATH) ElementNotFoundException.cpp -o ElementNotFoundException.o
	g++ -c $(INCLUDE_PATH) DuplicateElementException.cpp -o DuplicateElementException.o

